// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: backend/protos/jobqueue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	DedupKey      string                 `protobuf:"bytes,6,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RunAfter      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=run_after,json=runAfter,proto3" json:"run_after,omitempty"`
	Attempts      int32                  `protobuf:"varint,10,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Job) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetRunAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAfter
	}
	return nil
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{4}
}

func (x *DequeueResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{5}
}

func (x *AckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Requeue       bool                   `protobuf:"varint,2,opt,name=requeue,proto3" json:"requeue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_backend_protos_jobqueue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_jobqueue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_jobqueue_proto_rawDescGZIP(), []int{6}
}

func (x *NackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NackRequest) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

var File_backend_protos_jobqueue_proto protoreflect.FileDescriptor

const file_backend_protos_jobqueue_proto_rawDesc = "" +
	"\n" +
	"\x1dbackend/protos/jobqueue.proto\x12\vjobqueue.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tdedup_key\x18\x06 \x01(\tR\bdedupKey\x12.\n" +
	"\x04meta\x18\a \x03(\v2\x1a.jobqueue.v1.Job.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\trun_after\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\brunAfter\x12\x1a\n" +
	"\battempts\x18\n" +
	" \x01(\x05R\battempts\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x0eEnqueueRequest\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.jobqueue.v1.JobR\x03job\"!\n" +
	"\x0fEnqueueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0eDequeueRequest\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\"7\n" +
	"\x0fDequeueResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.jobqueue.v1.JobR\x04jobs\"\x1c\n" +
	"\n" +
	"AckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\vNackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\arequeue\x18\x02 \x01(\bR\arequeue2\x88\x02\n" +
	"\bJobQueue\x12D\n" +
	"\aEnqueue\x12\x1b.jobqueue.v1.EnqueueRequest\x1a\x1c.jobqueue.v1.EnqueueResponse\x12D\n" +
	"\aDequeue\x12\x1b.jobqueue.v1.DequeueRequest\x1a\x1c.jobqueue.v1.DequeueResponse\x126\n" +
	"\x03Ack\x12\x17.jobqueue.v1.AckRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x04Nack\x12\x18.jobqueue.v1.NackRequest\x1a\x16.google.protobuf.EmptyB\x16Z\x14backend/protos;protob\x06proto3"

var (
	file_backend_protos_jobqueue_proto_rawDescOnce sync.Once
	file_backend_protos_jobqueue_proto_rawDescData []byte
)

func file_backend_protos_jobqueue_proto_rawDescGZIP() []byte {
	file_backend_protos_jobqueue_proto_rawDescOnce.Do(func() {
		file_backend_protos_jobqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_protos_jobqueue_proto_rawDesc), len(file_backend_protos_jobqueue_proto_rawDesc)))
	})
	return file_backend_protos_jobqueue_proto_rawDescData
}

var file_backend_protos_jobqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_protos_jobqueue_proto_goTypes = []any{
	(*Job)(nil),                   // 0: jobqueue.v1.Job
	(*EnqueueRequest)(nil),        // 1: jobqueue.v1.EnqueueRequest
	(*EnqueueResponse)(nil),       // 2: jobqueue.v1.EnqueueResponse
	(*DequeueRequest)(nil),        // 3: jobqueue.v1.DequeueRequest
	(*DequeueResponse)(nil),       // 4: jobqueue.v1.DequeueResponse
	(*AckRequest)(nil),            // 5: jobqueue.v1.AckRequest
	(*NackRequest)(nil),           // 6: jobqueue.v1.NackRequest
	nil,                           // 7: jobqueue.v1.Job.MetaEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_backend_protos_jobqueue_proto_depIdxs = []int32{
	7, // 0: jobqueue.v1.Job.meta:type_name -> jobqueue.v1.Job.MetaEntry
	8, // 1: jobqueue.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: jobqueue.v1.Job.run_after:type_name -> google.protobuf.Timestamp
	0, // 3: jobqueue.v1.EnqueueRequest.job:type_name -> jobqueue.v1.Job
	0, // 4: jobqueue.v1.DequeueResponse.jobs:type_name -> jobqueue.v1.Job
	1, // 5: jobqueue.v1.JobQueue.Enqueue:input_type -> jobqueue.v1.EnqueueRequest
	3, // 6: jobqueue.v1.JobQueue.Dequeue:input_type -> jobqueue.v1.DequeueRequest
	5, // 7: jobqueue.v1.JobQueue.Ack:input_type -> jobqueue.v1.AckRequest
	6, // 8: jobqueue.v1.JobQueue.Nack:input_type -> jobqueue.v1.NackRequest
	2, // 9: jobqueue.v1.JobQueue.Enqueue:output_type -> jobqueue.v1.EnqueueResponse
	4, // 10: jobqueue.v1.JobQueue.Dequeue:output_type -> jobqueue.v1.DequeueResponse
	9, // 11: jobqueue.v1.JobQueue.Ack:output_type -> google.protobuf.Empty
	9, // 12: jobqueue.v1.JobQueue.Nack:output_type -> google.protobuf.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_backend_protos_jobqueue_proto_init() }
func file_backend_protos_jobqueue_proto_init() {
	if File_backend_protos_jobqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_protos_jobqueue_proto_rawDesc), len(file_backend_protos_jobqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_protos_jobqueue_proto_goTypes,
		DependencyIndexes: file_backend_protos_jobqueue_proto_depIdxs,
		MessageInfos:      file_backend_protos_jobqueue_proto_msgTypes,
	}.Build()
	File_backend_protos_jobqueue_proto = out.File
	file_backend_protos_jobqueue_proto_goTypes = nil
	file_backend_protos_jobqueue_proto_depIdxs = nil
}
